services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB={{project_name}}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7432:7432"

volumes:
  postgres_data: